{
 "title": "App별 메트릭 대시보드",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}, workload)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilisation (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, workload) (\n  namespace_workload_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$app\"}\n) \n/ \nsum by (namespace, workload) (\n  namespace_workload_pod_container:kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$app\"}\n)"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from limits)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, workload) (\n  namespace_workload_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$app\"}\n) \n/ \nsum by (namespace, workload) (\n  namespace_workload_pod_container:kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$app\"}\n)"
    }
   ]
  },
  {
   "title": "Memory Utilisation (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, workload) (\n  namespace_workload_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\", workload=~\"$app\"}\n) \n/ \nsum by (namespace, workload) (\n  namespace_workload_pod_container:kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", workload=~\"$app\"}\n)"
    }
   ]
  },
  {
   "title": "Memory Utilisation (from limits)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, workload) (\n  namespace_workload_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\", workload=~\"$app\"}\n) \n/ \nsum by (namespace, workload) (\n  namespace_workload_pod_container:kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", workload=~\"$app\"}\n)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (namespace, pod, workload) (namespace_workload_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}) unless on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (dead)"
    },
    {
     "expr": "sum by (namespace, pod, workload) (namespace_workload_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}) and on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (live)"
    },
    {
     "expr": "scalar(max(kube_resourcequota{namespace=\"$namespace\", type=\"hard\",resource=\"requests.cpu\"}))",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(max(kube_resourcequota{namespace=\"$namespace\", type=\"hard\",resource=\"limits.cpu\"}))",
     "legendFormat": "quota - limits"
    },
    {
     "expr": "sum by (workload) (namespace_workload_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"})",
     "legendFormat": "{{workload}} (Total)"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (pod, workload) (\n  namespace_workload_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\", workload=~\"$app\"}\n)"
    },
    {
     "expr": "sum by (pod, workload) (namespace_workload_pod_container:kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by (pod, workload) (namespace_workload_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\", workload=~\"$app\"}) / sum by (pod, workload) (namespace_workload_pod_container:kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by (pod, workload) (namespace_workload_pod_container:kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by (pod, workload) (namespace_workload_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\", workload=~\"$app\"}) / sum by (pod, workload) (namespace_workload_pod_container:kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, workload) (namespace_workload_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}) unless on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (dead)"
    },
    {
     "expr": "sum by (namespace, pod, workload) (namespace_workload_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}) and on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (live)"
    },
    {
     "expr": "scalar(max(kube_resourcequota{namespace=\"$namespace\", type=\"hard\",resource=\"requests.memory\"}))",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(max(kube_resourcequota{namespace=\"$namespace\", type=\"hard\",resource=\"limits.memory\"}))",
     "legendFormat": "quota - limits"
    },
    {
     "expr": "sum by (workload) (namespace_workload_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"})",
     "legendFormat": "{{workload}} (Total)"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod, workload) (namespace_workload_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by (pod, workload) (namespace_workload_pod_container:kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by (pod, workload) (namespace_workload_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\", workload=~\"$app\"}) / sum by (pod, workload) (namespace_workload_pod_container:kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by (pod, workload) (namespace_workload_pod_container:kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by (pod, workload) (namespace_workload_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\", workload=~\"$app\"}) / sum by (pod, workload) (namespace_workload_pod_container:kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by (pod, workload) (namespace_workload_pod_container:container_memory_rss{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by (pod, workload) (namespace_workload_pod_container:container_memory_cache{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by (workload) (max by (namespace, pod, container, workload) (container_memory_swap{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container!=\"\"} * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"}))"
    },
    {
     "expr": "kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (pod, workload) (8 * namespace_workload_pod_container:container_network_receive_bytes_total{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by (pod, workload) (8 * namespace_workload_pod_container:container_network_transmit_bytes_total{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by (pod, workload) (max by (namespace, pod, workload) (rate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"}))"
    },
    {
     "expr": "sum by (pod, workload) (max by (namespace, pod, workload) (rate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"}))"
    },
    {
     "expr": "sum by (pod, workload) (max by (namespace, pod, workload) (rate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"}))"
    },
    {
     "expr": "sum by (pod, workload) (max by (namespace, pod, workload) (rate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"}))"
    },
    {
     "expr": "kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, workload) (8 * namespace_workload_pod_container:container_network_receive_bytes_total{namespace=\"$namespace\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}) unless on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (dead)"
    },
    {
     "expr": "sum by (namespace, pod, workload) (8 * namespace_workload_pod_container:container_network_receive_bytes_total{namespace=\"$namespace\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}) and on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (live)"
    },
    {
     "expr": "sum by (workload) (8 * namespace_workload_pod_container:container_network_receive_bytes_total{namespace=\"$namespace\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"})",
     "legendFormat": "{{workload}} (Total)"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, workload) (8 * namespace_workload_pod_container:container_network_transmit_bytes_total{namespace=\"$namespace\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}) unless on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (dead)"
    },
    {
     "expr": "sum by (namespace, pod, workload) (8 * namespace_workload_pod_container:container_network_transmit_bytes_total{namespace=\"$namespace\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}) and on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (live)"
    },
    {
     "expr": "sum by (workload) (8 * namespace_workload_pod_container:container_network_transmit_bytes_total{namespace=\"$namespace\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"})",
     "legendFormat": "{{workload}} (Total)"
    }
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, workload) (max by (namespace, pod, workload) (rate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"})) unless on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (dead)"
    },
    {
     "expr": "sum by (namespace, pod, workload) (max by (namespace, pod, workload) (rate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"})) and on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (live)"
    },
    {
     "expr": "sum by (workload) (max by (namespace, pod, workload) (rate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"}))",
     "legendFormat": "{{workload}} (Total)"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, workload) (max by (namespace, pod, workload) (rate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"})) unless on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (dead)"
    },
    {
     "expr": "sum by (namespace, pod, workload) (max by (namespace, pod, workload) (rate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"})) and on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (live)"
    },
    {
     "expr": "sum by (workload) (max by (namespace, pod, workload) (rate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"}))",
     "legendFormat": "{{workload}} (Total)"
    }
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, workload) (max by (namespace, pod, workload) (rate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"})) unless on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (dead)"
    },
    {
     "expr": "sum by (namespace, pod, workload) (max by (namespace, pod, workload) (rate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"})) and on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (live)"
    },
    {
     "expr": "sum by (workload) (max by (namespace, pod, workload) (rate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"}))",
     "legendFormat": "{{workload}} (Total)"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, workload) (max by (namespace, pod, workload) (rate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"})) unless on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (dead)"
    },
    {
     "expr": "sum by (namespace, pod, workload) (max by (namespace, pod, workload) (rate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"})) and on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (live)"
    },
    {
     "expr": "sum by (workload) (max by (namespace, pod, workload) (rate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval]) * on (namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$app\"}))",
     "legendFormat": "{{workload}} (Total)"
    }
   ]
  },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "ceil(sum by(namespace, pod, workload) ((namespace_workload_pod_container:container_fs_reads_bytes_total{namespace=\"$namespace\"} + namespace_workload_pod_container:container_fs_writes_bytes_total{namespace=\"$namespace\"}) * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"})) unless on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (dead)"
    },
    {
     "expr": "ceil(sum by(namespace, pod, workload) ((namespace_workload_pod_container:container_fs_reads_bytes_total{namespace=\"$namespace\"} + namespace_workload_pod_container:container_fs_writes_bytes_total{namespace=\"$namespace\"}) * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"})) and on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (live)"
    },
    {
     "expr": "ceil(sum by(workload) ((namespace_workload_pod_container:container_fs_reads_bytes_total{namespace=\"$namespace\"} + namespace_workload_pod_container:container_fs_writes_bytes_total{namespace=\"$namespace\"}) * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}))",
     "legendFormat": "{{workload}} (Total)"
    }
   ]
  },
  {
   "title": "ThroughPut(Read+Write)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(namespace, pod, workload) ((namespace_workload_pod_container:container_fs_reads_bytes_total{namespace=\"$namespace\"} + namespace_workload_pod_container:container_fs_writes_bytes_total{namespace=\"$namespace\"}) * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}) unless on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (dead)"
    },
    {
     "expr": "sum by(namespace, pod, workload) ((namespace_workload_pod_container:container_fs_reads_bytes_total{namespace=\"$namespace\"} + namespace_workload_pod_container:container_fs_writes_bytes_total{namespace=\"$namespace\"}) * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}) and on(namespace, pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} @ end() == 1)",
     "legendFormat": "{{pod}} (live)"
    },
    {
     "expr": "sum by(workload) ((namespace_workload_pod_container:container_fs_reads_bytes_total{namespace=\"$namespace\"} + namespace_workload_pod_container:container_fs_writes_bytes_total{namespace=\"$namespace\"}) * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"})",
     "legendFormat": "{{workload}} (Total)"
    }
   ]
  },
  {
   "title": "Current Storage IO",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum by(pod, workload) (namespace_workload_pod_container:container_fs_reads_bytes_total{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by(pod, workload) (namespace_workload_pod_container:container_fs_writes_bytes_total{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by(pod, workload) (namespace_workload_pod_container:container_fs_reads_bytes_total{namespace=\"$namespace\", workload=~\"$app\"} + namespace_workload_pod_container:container_fs_writes_bytes_total{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by(pod, workload) (namespace_workload_pod_container:container_fs_reads_bytes_total{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by(pod, workload) (namespace_workload_pod_container:container_fs_writes_bytes_total{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "sum by(pod, workload) (namespace_workload_pod_container:container_fs_reads_bytes_total{namespace=\"$namespace\", workload=~\"$app\"} + namespace_workload_pod_container:container_fs_writes_bytes_total{namespace=\"$namespace\", workload=~\"$app\"})"
    },
    {
     "expr": "kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} * on(namespace, pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$app\"}"
    }
   ]
  }
 ]
}