apiVersion: v1
kind: Service
metadata:
  name: egress-wan4
  namespace: kube-vip-egress
  labels:
    app.kubernetes.io/name: kube-vip-egress
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.88.222" 
    kube-vip.io/allow-reconcile-without-endpoints: "true"
spec:
  type: LoadBalancer
  loadBalancerClass: myyrakle.io/egress-vip
  externalTrafficPolicy: Cluster
  ports:
    - name: unused
      port: 65535
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: egress-wan4
  namespace: kube-vip-egress
  labels:
    kubernetes.io/service-name: egress-wan4
addressType: IPv4
endpoints: []
