{
 "title": "Lightweight APM for OpenTelemetry",
 "description": "Lightweight APM dashboard for monitoring OpenTelemetry-based services.  \n\nInstrument your applications using OpenTelemetry SDKs and send traces, metrics, and logs to Tempo for traces, a Prometheus-compatible database like Mimir for metrics, and Loki for logs. This dashboard provides a centralized view of your application's health and performance.  \n\nFor a fully managed observability stack, consider using Grafana Cloud.  \n\nLearn more about this dashboard on https://github.com/cyrille-leclerc/opentelemetry-service-dashboard.",
 "tags": [
  "opentelemetry",
  "APM"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Metrics", "query": "prometheus" },
   { "name": "tempo_datasource", "label": "Traces", "query": "tempo" },
   { "name": "loki_datasource", "label": "Logs", "query": "loki" },
   {
    "name": "service_namespace",
    "label": "service.namespace",
    "query": {}
   },
   {
    "name": "service_name",
    "label": "service.name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><img src=\"https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png\" alt=\"OpenTelemetry Icon\" width=\"25\" height=\"\"> Service ${service_namespace}/${service_name}</h1>"
   }
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received in the past 24h.",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(sum by (service_namespace, service_name) (target_info{service_namespace=\"$service_namespace\", service_name=\"$service_name\"}) or absent{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest logs received",
   "type": "stat",
   "description": "Shows the timestamp of the latest logs received in the past 24h.",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"$service_name\", service_namespace=\"$service_namespace\"} [5m]))"
    }
   ]
  },
  {
   "title": "Latest traces received",
   "type": "stat",
   "description": "Shows the timestamp of the latest span received in the past 24h.",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "filters": [
      {
       "id": "0344fb49",
       "operator": "=",
       "scope": "resource",
       "tag": "service.namespace",
       "value": [ "$service_namespace" ],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service_name" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.namespace=\"$service_namespace\" && resource.service.name=\"$service_name\"} | count_over_time()",
     "tableType": "traces"
    }
   ]
  },
  { "title": "Server HTTP RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "HTTP endpoints aggregation on the `http.server.request.duration` metric.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, job) (rate(http_server_request_duration_seconds_bucket{service_name=\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, job) (rate(http_server_request_duration_seconds_bucket{job=\"$service_namespace/$service_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "avg by(job) (rate(http_server_request_duration_seconds_sum{job=\"$service_namespace/$service_name\"}[$__rate_interval])) / avg by(job) (rate(http_server_request_duration_seconds_count{job=\"$service_namespace/$service_name\"}[$__rate_interval]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "description": "HTTP endpoints aggregation on the `http.server.request.duration` metric. \n\nErrors are identified by   `http.response.status_code=~\"5..\"`.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum without(http_status_code, error_type, instance) (rate(http_server_request_duration_seconds_count{service_namespace=\"$service_namespace\", service_name=\"$service_name\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval])) * 100) / sum without(http_status_code, error_type, instance) (rate(http_server_request_duration_seconds_count{service_name=\"$service_name\", service_namespace=\"$service_namespace\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "HTTP endpoints aggregation on the `http.server.request.duration` metric.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_count{service_namespace=\"$service_namespace\", service_name=\"$service_name\"}[$__rate_interval])) by (service_namespace, service_name)) * $__interval_ms / 1000",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "Inbound Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP Operations",
   "type": "table",
   "description": "Inbound HTTP operations of the service (aka HTTP endpoints) based on the `http.server.request.duration` metric.\n\nErrors are identified by `http.response.status_code=~\"5..\"`.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "\n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{service_namespace=\"$service_namespace\", service_name=\"$service_name\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n    ",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "(\n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{job=~\"$service_namespace/$service_name\", http_response_status_code=~\"5..\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n     / \n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n    ) or (0 * \n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n    )",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "\n        histogram_quantile(\n            0.99,\n            sum by (le, operation) (\n                label_join(\n                rate(http_server_request_duration_seconds_bucket{job=~\"$service_namespace/$service_name\"}[5m]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n                )\n            )\n        )\n    ",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Outbound Services and Databases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Outbound HTTP Services",
   "type": "table",
   "description": "HTTP calls made by the service based on the `http.client.request.duration` metric.\n\nCalls broken done by remote `server.address` and by `http.request.method`.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpclientrequestduration",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "\n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{service_namespace=\"$service_namespace\", service_name=\"$service_name\", server_address!=\"\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n    ",
     "legendFormat": "{{server_address}} {{http_request_method}} {{url_template}}"
    },
    {
     "expr": "(\n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{service_namespace=\"$service_namespace\", service_name=\"$service_name\", server_address!=\"\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n     / \n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{service_namespace=\"$service_namespace\", service_name=\"$service_name\", server_address!=\"\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n    ) or (0 * \n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{service_namespace=\"$service_namespace\", service_name=\"$service_name\", server_address!=\"\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n    )",
     "legendFormat": "{{server_address}} {{http_request_method}} {{url_template}}"
    },
    {
     "expr": "\nhistogram_quantile(\n    0.99,\n    sum by (le, outbound_service) (\n        label_join(\n        rate(http_client_request_duration_seconds_bucket{service_namespace=\"$service_namespace\", service_name=\"$service_name\", server_address!=\"\"}[5m]),\n        \"outbound_service\",\n        \" \",\n        \"server_address\",\n        \"http_request_method\",\n        \"url_template\"\n        )\n    )\n)",
     "legendFormat": "{{server_address}} {{http_request_method}} {{url_template}}"
    }
   ]
  },
  {
   "title": "Outbound Databases",
   "type": "table",
   "description": "DB calls made by the service based on the `db.client.operation.duration` metric.\n\nCalls broken down by `server.address` and `db.namespace`.\n\nSee https://opentelemetry.io/docs/specs/semconv/database/database-metrics/#metric-dbclientoperationduration\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (database) (\n    label_join(\n        rate(db_client_operation_duration_seconds_count{service_namespace=\"$service_namespace\", service_name=\"$service_name\", db_system_name!=\"\"}[$__rate_interval]),\n        \"database\",\n        \"/\",\n        \"db_system_name\",\n        \"span_name\"\n    )\n)\n    ",
     "legendFormat": "{{server_address}} {{db_namespace}}"
    },
    {
     "expr": "(\n        sum by (database) (\n            label_join(\n                rate(db_client_operation_duration_seconds_count{service_namespace=\"$service_namespace\", service_name=\"$service_name\", db_error!=\"\", db_system_name!=\"\"}[$__rate_interval]),\n                \"database\",\n                \"/\",\n                \"db_system_name\",\n                \"span_name\"\n            )\n        )\n     / \n        sum by (database) (\n            label_join(\n                rate(db_client_operation_duration_seconds_count{service_namespace=\"$service_namespace\", service_name=\"$service_name\", db_system_name!=\"\"}[$__rate_interval]),\n                \"database\",\n                \"/\",\n                \"db_system_name\",\n                \"span_name\"\n            )\n        )\n    ) or (0 * \n        sum by (database) (\n            label_join(\n                rate(db_client_operation_duration_seconds_count{service_namespace=\"$service_namespace\", service_name=\"$service_name\", db_system_name!=\"\"}[$__rate_interval]),\n                \"database\",\n                \"/\",\n                \"db_system_name\",\n                \"span_name\"\n            )\n        )\n    )",
     "legendFormat": "{{server_address}} {{db_namespace}}"
    },
    {
     "expr": "\nhistogram_quantile(\n    0.99,\n    sum by (le, database) (\n        label_join(\n        rate(db_client_operation_duration_seconds_bucket{service_namespace=\"$service_namespace\", service_name=\"$service_name\", db_system_name!=\"\"}[5m]),\n            \"database\",\n            \"/\",\n            \"db_system_name\",\n            \"span_name\"\n        )\n    )\n)",
     "legendFormat": "{{server_address}} {{db_namespace}}"
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "table",
   "description": "Traces containing a span emitted by the service",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "filters": [
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service_name" ],
       "valueType": "string"
      },
      {
       "id": "6997e808",
       "operator": "=",
       "scope": "resource",
       "tag": "deployment.environment.name",
       "value": [ "$deployment_environment_name" ],
       "valueType": "string"
      },
      {
       "id": "e9f0e855",
       "operator": "=",
       "scope": "resource",
       "tag": "service.namespace",
       "value": [ "$service_namespace" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"$service_name\" && resource.service.namespace=\"$service_namespace\" && name != \"/shops/ping\" && span.primary = true}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM",
     "type": "table",
     "description": "For JVM based services like Java or Kotlin, the JVM metrics.\n\nSee https://opentelemetry.io/docs/specs/semconv/runtime/jvm-metrics/",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum by(instance) (jvm_cpu_recent_utilization_ratio{job=\"$service_namespace/$service_name\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(instance) (rate(jvm_gc_duration_seconds_sum{job=\"$service_namespace/$service_name\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}