{
 "title": "OpenTelemetry APM",
 "description": "A language-agnostic application performance management(APM) with OpenTelemetry, Grafana, and Prometheus.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "app", "label": "Application", "query": { "query": "label_values(service_name)" } },
   { "name": "route", "label": "Route", "query": { "query": "label_values(http_route)" } },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(service_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", service_namespace=\"$env\", http_route=~\"$route\"}[$__range])) by(service_name)",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", http_route=~\"$route\"}) by(service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Distribution",
   "type": "piechart",
   "description": "request amount distribution",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", service_namespace=\"$env\", http_route=~\"$route\"}[$__range])) by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Loading Distribution",
   "type": "piechart",
   "description": "cumulative latency distribution",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", service_namespace=\"$env\", http_route=~\"$route\"}[$__range])) by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Overall Request Rate",
   "type": "gauge",
   "description": "overall request rate per minute over last 3 minutes",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", service_namespace=\"$env\", http_route=~\"$route\"}[3m])*60)"
    }
   ]
  },
  {
   "title": "Overall Error Rate",
   "type": "gauge",
   "description": "percentage of HTTP status 5xx in all requests",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", service_namespace=\"$env\",status_code=~\"STATUS_CODE_ERROR\"})/sum(http_server_request_duration_seconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", service_namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "request rate per minute over last 3 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=\"$app\", service_namespace=\"$env\", span_kind=\"SPAN_KIND_SERVER\", http_route=~\"$route\"}[3m])*60)  by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "PR95 Latency",
   "type": "timeseries",
   "description": "PR95 latency over last 3 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", service_namespace=\"$env\", http_route=~\"$route\"}[3m])) by (le, span_name))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "bargauge",
   "description": "by route and http status code",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(increase(http_server_request_duration_seconds_sum{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", service_namespace=\"$env\", http_status_code!=\"\", http_route=~\"$route\"}[$__range]) / increase(http_server_request_duration_seconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", service_namespace=\"$env\", http_status_code!=\"\", http_route=~\"$route\"}[$__range]))",
     "legendFormat": "[{{http_status_code}}] {{span_name}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "description": "Details of each API",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=\"$app\", service_namespace=\"$env\", http_route=~\"$route\", span_kind=\"SPAN_KIND_SERVER\"}[3m])*60) by(service_name, http_method, http_route)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_milliseconds_bucket{service_name=\"$app\", service_namespace=\"$env\", http_route=~\"$route\", span_kind=\"SPAN_KIND_SERVER\"}[3m])) by (le, service_name, http_method, http_route))"
    },
    {
     "expr": "sum(http_server_request_duration_milliseconds_count{service_name=\"$app\", service_namespace=\"$env\", http_route=~\"$route\", span_kind=\"SPAN_KIND_SERVER\", http_status_code!~\"2.*|3.*\"}) by(service_name, http_method, http_route) / sum(http_server_request_duration_milliseconds_count{service_name=\"$app\", http_route=~\"$route\", span_kind=\"SPAN_KIND_SERVER\"}) by(service_name, http_method, http_route)"
    }
   ]
  }
 ]
}