{
 "title": "NVIDIA GPU Dashboard",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, Hostname)"
   },
   {
    "name": "gpu",
    "query": "query_result(label_join(max by (Hostname, gpu, UUID) (DCGM_FI_DEV_GPU_TEMP{Hostname=~\"${node}\"}), \"gpu_label\", \" - \", \"Hostname\", \"gpu\"))"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Inventory",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (Hostname, gpu, UUID, modelName) (DCGM_FI_DEV_GPU_TEMP{Hostname=~\"${node}\", UUID=~\"${gpu}\"})"
    },
    {
     "expr": "max by (Hostname, gpu, UUID, modelName) (DCGM_FI_DEV_FB_TOTAL{Hostname=~\"${node}\", UUID=~\"${gpu}\"}) or (max by (Hostname, gpu, UUID, modelName) (DCGM_FI_DEV_FB_USED{Hostname=~\"${node}\", UUID=~\"${gpu}\"}) + max by (Hostname, gpu, UUID, modelName) (DCGM_FI_DEV_FB_FREE{Hostname=~\"${node}\", UUID=~\"${gpu}\"}))"
    },
    {
     "expr": "max by (Hostname, gpu, UUID, modelName) (DCGM_FI_DEV_FB_USED{Hostname=~\"${node}\", UUID=~\"${gpu}\"})"
    },
    {
     "expr": "max by (Hostname, gpu, UUID, modelName) (DCGM_FI_DEV_GPU_UTIL{Hostname=~\"${node}\", UUID=~\"${gpu}\"})"
    },
    {
     "expr": "max by (Hostname, gpu, UUID, modelName) (DCGM_FI_DEV_SM_CLOCK{Hostname=~\"${node}\", UUID=~\"${gpu}\"}) * 1000000"
    },
    {
     "expr": "max by (Hostname, gpu, UUID, modelName) (DCGM_FI_DEV_GPU_TEMP{Hostname=~\"${node}\", UUID=~\"${gpu}\"})"
    },
    {
     "expr": "max by (Hostname, gpu, UUID, modelName) (DCGM_FI_DEV_POWER_USAGE{Hostname=~\"${node}\", UUID=~\"${gpu}\"})"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{Hostname=~\"${node}\", UUID=~\"${gpu}\"}",
     "legendFormat": "{{Hostname}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{Hostname=~\"${node}\", UUID=~\"${gpu}\"})"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{Hostname=~\"${node}\", UUID=~\"${gpu}\"}",
     "legendFormat": "{{Hostname}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{Hostname=~\"${node}\", UUID=~\"${gpu}\"})"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{Hostname=~\"${node}\", UUID=~\"${gpu}\"} * 1000000",
     "legendFormat": "{{Hostname}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{Hostname=~\"${node}\", UUID=~\"${gpu}\"}",
     "legendFormat": "{{Hostname}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=~\"${node}\", UUID=~\"${gpu}\"}",
     "legendFormat": "{{Hostname}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{Hostname=~\"${node}\", UUID=~\"${gpu}\"}",
     "legendFormat": "{{Hostname}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "Allocation Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(Hostname, gpu, modelName, GPU_I_PROFILE, GPU_I_ID, exported_namespace, exported_pod) (DCGM_FI_DEV_SM_CLOCK{Hostname=~\"${node}\", UUID=~\"${gpu}\"})",
     "legendFormat": "{{Hostname}} - {{gpu}}"
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "PCIe retry rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "avg by(Hostname, gpu) (rate(DCGM_FI_DEV_PCIE_REPLAY_COUNTER{Hostname=~\"${node}\", UUID=~\"${gpu}\"}[$__rate_interval]))",
     "legendFormat": "{{Hostname}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "XID error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "avg by(Hostname, gpu) (DCGM_FI_DEV_XID_ERRORS{Hostname=~\"${node}\", UUID=~\"${gpu}\"})",
     "legendFormat": "{{Hostname}} - {{gpu}}"
    }
   ]
  }
 ]
}