name: Deploy AWS API

on:
  workflow_dispatch:
    inputs:
      server_name:
        required: true
        type: choice
        description: "서버 이름"
        default: "main-api"
        options:
          - "main-api"
      environment:
        required: true
        type: choice
        description: "배포 환경"
        default: "dev"
        options:
          - "dev"
          - "qa"
          - "prod"
          
env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 4444444444.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: ${{ inputs.server_name }}-${{ inputs.environment }}
  API_IMAGE_TAG: v${{ github.sha }}
  ECS_TASK_DEFINITION: ${{ inputs.server_name }}-${{ inputs.environment }}
  ECS_CONTAINER_NAME: ${{ inputs.server_name }}-${{ inputs.environment }}
  ECS_SERVICE_NAME: ${{ inputs.server_name }}-${{ inputs.environment }}
  ECS_CLUSTER_NAME: some-cluster
  
run-name: Deploy AWS API ${{ inputs.server_name }} ${{ inputs.environment }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build And Push (API)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./packages/functions/Dockerfile
          target: dev
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.API_IMAGE_TAG }}
          platforms: linux/amd64 # if you want to build for multiple platforms, you can specify them here
          build-args: |
            GH_TOKEN=${{ secrets.GH_TOKEN }}
          secrets: GH_TOKEN=${{ secrets.GH_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.ECS_CONTAINER_NAME }}
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.API_IMAGE_TAG }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE_NAME }}
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: false